name: ktusch-sync database backup

on:
  schedule:
    - cron:  '* * * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Connect to remote server and perform backup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker exec -t ktusch-postgres pg_dumpall -c -U postgres > ~/backups/dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
