name: ktusch-sync deploy

on:
  push:
    branches: [ master ]


jobs:
  deploy-to-remote-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Build Docker Image
      run: |
        docker build --tag ktusch-sync:${{ github.run_number }} --build-arg GOOGLE_CREDENTIALS_DECRYPT="${{ secrets.GOOGLE_CREDENTIALS_DECRYPT }}" .
    
    - name: Save docker image to .tar
      run: |
        docker save --output=ktusch-sync:${{ github.run_number }}.tar ktusch-sync:${{ github.run_number }}

    - name: Copy .tar Image to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.PRIVATE_KEY }}
        source: "ktusch-sync:${{ github.run_number }}.tar"
        target: "~/"

    - name: Load and run Docker Image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          docker rm -f ktusch-sync || true
          docker prune --all --force
          cd ~
          docker load --input=ktusch-sync:${{ github.run_number }}.tar
          rm -f ktusch-sync:${{ github.run_number }}.tar
          docker run -d --network=ktusch-sync-net -p 5000:5000 -v /var/log/ktusch-sync:/app/business/logs --name ktusch-sync -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} -e HOST=ktusch-postgres -e USERNAME=${{ secrets.USERNAME }} -e PASSWORD=${{ secrets.PASSWORD }} -e HUBSPOT_API_KEY=${{ secrets.HUBSPOT_API_KEY }} ktusch-sync:${{ github.run_number }}
