name: ktusch-sync deploy

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd ~
          ls -a
        host: ${{ secrets.HOST }}
        user: root
        key: ${{ secrets.PRIVATE_KEY}}

    - name: Install test requirements
      run: |
        docker build --tag ktusch-sync \ 
            --build-arg GOOGLE_CREDENTIALS_DECRYPT="${{ secrets.GOOGLE_CREDENTIALS_DECRYPT }}" \
            .
        docker images
  
