name: ktusch-sync deploy

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Build Docker Image
      run: |
        docker build --tag ktusch-sync:${{ github.run_number }} --build-arg GOOGLE_CREDENTIALS_DECRYPT="${{ secrets.GOOGLE_CREDENTIALS_DECRYPT }}" .
    
    - name: Save docker image to .tar
      run: |
        docker save --output=ktusch-sync:${{ github.run_number }}.tar ktusch-sync:${{ github.run_number }}
    
    - name: Copy .tar Image to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: ${{ secrets.PASSWORD }}
        source: ktusch-sync:${{ github.run_number }}.tar
        target: ~/
        
