name: ktusch-sync tests

on:
  pull_request:
    branches: [ master ]

jobs:
  run-pytest-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install test requirements
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r tests/tests_requirements.txt
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Decrypt Google Credentials
      env:
        GOOGLE_CREDENTIALS_DECRYPT: ${{ secrets.GOOGLE_CREDENTIALS_DECRYPT }}
      run: |
        ./oauth_decrypt.sh

    
    - name: Test with pytest
      run: |
        pytest -v -x
      env:
        HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}    
